// import "./globals.css";
// import { Inter } from "next/font/google";

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// export const metadata = {
//   title: "Crime Sense",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={inter.variable}>
//       <head>
//         <link rel="icon" type="image/png" href="/fav.png" />
//         <meta charSet="utf-8" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </head>
//       <body className="antialiased bg-white text-black">{children}</body>
//     </html>
//   );
// }


// app/layout.tsx
// import "./globals.css";
// import { Inter } from "next/font/google";
// import NavBar from "./components/NavBar";

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

// export const metadata = {
//   title: "Crime Sense",
//   description: "Real-time video-based crime classification",
// };

// // app/layout.tsx
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className={inter.variable}>
//       <head>
//         <link rel="icon" href="/fav.png" />
//         <meta charSet="utf-8" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//       </head>
//       <body className="antialiased bg-amber-100 min-h-screen text-gray-800">
//         <NavBar />
//         {/* add top padding so your fixed navbar doesn’t cover content */}
//         <main className="pt-16 px-4 md:px-16 lg:px-32">{children}</main>
//       </body>
//     </html>
//   );
// }


import Script from 'next/script'
import { ReactNode } from 'react'
// import clsx from 'clsx'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import dynamic from 'next/dynamic'
import { Hanken_Grotesk } from 'next/font/google'
import '../../public/assets/tailwind.css'

const LayoutComponent = dynamic(() => import('@/app/components/Layout'), {
  ssr: true, // Only load on client-side
})
interface LayoutProps {
  children: ReactNode
}

const hanken = Hanken_Grotesk({
  subsets: ['latin'],
})

const Layout = ({ children }: LayoutProps) => {
  return (
    <html lang="en" className={'h-full scroll-smooth antialiased'}>
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>
          Crime Sense
        </title>
        <meta
          name="description"
          content="Video based Crime Classification"
        />
        <meta name="author" content="Binocs" />
        <meta httpEquiv="Content-Language" content="en" />

        <link rel="canonical" href="https://binocs.co" />
        <link rel="icon" href="/favicon.ico" />

        <meta
          property="og:title"
          content="Crime Sense"
        />
        <meta
          property="og:description"
          content="Innovative fintech product that enhances operational efficiency and risk management for institutional lenders and borrowers, leveraging technologies such as workflow automation, data analytics, and AI."
        />
        <meta
          property="og:image"
          content="https://binocs.co/assets/images/BinocsLogo.svg"
        />
        <meta property="og:url" content="https://binocs.co" />

        {/* Google Tag Manager */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-RDVYF7JY8E"
        />
        <Script
          id="gtag-init"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-RDVYF7JY8E');
            `,
          }}
        />
      </head>

      <body className={hanken.className}>
        <AppRouterCacheProvider options={{ key: 'css', enableCssLayer: true }}>
          <LayoutComponent>{children}</LayoutComponent>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}

export default Layout

